### ISSUE TITLE
Altura hace que la UI se vea mal.

### ISSUE THREAD

**Issue by marcorichetta** [leo10099/dev-job-finder#3]
https://github.com/leo10099/dev-job-inspector/blob/eea6fd51b341f869dc8589d8dd7949bb79cc3a7b/src/assets/scss/pages/Features.scss#L20

![imagen](https://user-images.githubusercontent.com/19599150/50937570-0fb6f380-1453-11e9-9514-359ffb36596e.png)

Probando con 170px o menos no colapsa y se sigue viendo bien en mobile.

Además la primera imagen queda un poco más abajo que las otras, aunque no puedo encontrar la propiedad. Parece ser algun padding o margin.

**Comment by leo10099** [comment]
Hola! ¿En qué navegador y resolución se queda así cortado? No estoy logrando reproducirlo.

**Comment by leo10099** [comment]
Gracias, lo estoy viendo, creo que la propiedad que citaste simplemente no está sumando nada y al sacarla no he visto efectos negativos.

**Comment by leanhanc** [comment]
Hola!
Estuve viendo y no logré reproducir que se vean las cards como en el screenshot. ¿En qué resolución y navegador sucede?

**Comment by marcorichetta** [comment]
Perdón, no tengo una pc en este momento. 1366 x 768 en Firefox 64 creo. KDE
Neon 18.04.

**Comment by marcorichetta** [comment]
Ahora sí estoy desde la notebook.
- KDE Neon 5.14 (Ubuntu 18.04)
- Firefox 65
- Resolución: 1366 * 768

**Comment by leanhanc** [comment]
Se rediseño el sitio con otra UI library.
